export {
  SIGNAL_ARITHMETIC_POLICY_VERSION,
  SIGNAL_DECIMAL_MAX_PRECISION,
  SIGNAL_DECIMAL_MAX_SCALE,
  addSignalDecimals,
  compareSignalDecimals,
  createSignalDecimal,
  multiplySignalDecimalByCount,
  multiplySignalDecimals,
  type SignalDecimal,
} from './arithmetic.js';
export {
  BREAKOUT_PLUS_VOLUME_DEFINITION_VERSION,
  CANONICAL_REVISION_SCHEMA_VERSION,
  DATA_QUALITY_POLICY_VERSION,
  FEATURE_RESULT_SCHEMA_VERSION,
  MAX_LOOKBACK_BARS,
  MIN_LOOKBACK_BARS,
  NYSE_CALENDAR_SNAPSHOT_VERSION,
  SIGNAL_CONFIGURATION_SCHEMA_VERSION,
  SIGNAL_EVALUATION_SCHEMA_VERSION,
  SIGNAL_TRANSITION_SCHEMA_VERSION,
  createSignalConfiguration,
  semanticVersions,
  serializeSignalConfiguration,
  type SignalConfiguration,
  type SignalConfigurationInput,
  type SignalSemanticVersions,
} from './configuration.js';
export type {
  BreakoutDirection,
  CanonicalRevisionSignalPort,
  ExactSignalValue,
  FeatureResult,
  FeatureSuppressionReason,
  FiredSignalEvaluation,
  NotFiredSignalEvaluation,
  ReadyFeatureResult,
  SignalEvaluation,
  SignalEvaluationBar,
  SignalEvaluationMode,
  SignalEvaluationTransition,
  SignalEvidenceReference,
  SignalInvalidationCondition,
  SignalOccurrence,
  SignalTransitionKind,
  SignalUnits,
  SuppressedFeatureResult,
  SuppressedSignalEvaluation,
  VolumeComparisonEvidence,
} from './contracts.js';
export { evaluateBreakoutPlusVolume } from './evaluation.js';
export { SignalError, type SignalErrorCode } from './errors.js';
export {
  MAX_FEATURE_STATE_BARS_PER_INSTRUMENT,
  affectedEvaluationEventIds,
  computeFeatureResult,
  type ComputeFeatureResultInput,
} from './features.js';
export {
  featureResultIdentity,
  serializeFeatureResult,
  serializeSignalEvaluation,
  serializeSignalTransition,
  signalEvaluationIdentity,
  signalOccurrenceIdentity,
  signalTransitionIdentity,
  type SignalEvaluationIdentityMaterial,
} from './serialization.js';
export { createSignalTransition, type CreateSignalTransitionInput } from './transitions.js';
export {
  createSignalReplayRecording,
  isVerifiedSignalReplayRecording,
  verifySignalReplayRecording,
} from './replay/recording.js';
export {
  persistVerifiedSignalReplay,
  projectVerifiedSignalReplay,
  serializeSignalReplayOutput,
  verifySignalReplayProjection,
} from './replay/replay.js';
export {
  MAX_SIGNAL_REPLAY_ASSOCIATIONS,
  MAX_SIGNAL_REPLAY_CATALOG_EVENTS,
  MAX_SIGNAL_REPLAY_RECORDING_CHARACTERS,
  MAX_SIGNAL_REPLAY_SCHEDULE_ENTRIES,
  SIGNAL_REPLAY_CATALOG_VERSION,
  SIGNAL_REPLAY_MANIFEST_VERSION,
  SIGNAL_REPLAY_OUTPUT_VERSION,
  SIGNAL_REPLAY_RECORDING_VERSION,
  SIGNAL_REPLAY_SCHEDULE_VERSION,
  type SignalReplayActiveOccurrence,
  type SignalReplayArtifact,
  type SignalReplayAssociation,
  type SignalReplayCanonicalOutput,
  type SignalReplayCatalog,
  type SignalReplayLatestEvaluation,
  type SignalReplayManifest,
  type SignalReplayPersistencePort,
  type SignalReplayProjection,
  type SignalReplayRecordingInput,
  type SignalReplaySchedule,
  type SignalReplayScheduleEntry,
  type SignalReplaySourceMetadata,
  type SignalReplayTargetDescriptor,
  type VerifiedSignalReplayRecording,
} from './replay/types.js';
